version: '3'

services:
  path-pilot-db-8:
    image: mysql:8.0.3
    container_name: path-pilot-db-8
    environment:
      - MYSQL_USER=pathpilot
      - MYSQL_DATABASE=path-pilot
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=path-pilot
    ports:
      - "27017:27017"

  my-app:
    image: quentinou/path-pilotapi
    container_name: api
    ports:
      - "80:80"
    depends_on:
      - path-pilot-db-8
      - mongodb