version: '3'

services:
  path-pilot-db-8:
    image: mysql:8.3
    container_name: path-pilot-db-8
    environment:
      - MYSQL_USER=pathpilot
      - MYSQL_DATABASE=path-pilot
      - MYSQL_PASSWORD=pathpilot
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
