services:
  # Service configuration for MySQL database
  mysql:
    image: mysql:8.0.3  # Specifies the MySQL image version 8.0.3
    container_name: path-pilot-db-8  # Names the container as 'path-pilot-db-8'
    env_file:
      - .env  # Loads environment variables from the .env file
    environment: # sets the environment variables for the container
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d  # Mounts the 'init' directory to the MySQL initialization directory
    ports:
      - "3306:3306"  # Maps port 3306 of the host to port 3306 of the container, wich is the default MySQL port
    command: --character-set-server=utf8 --collation-server=utf8_general_ci  # Sets the character set and collation for the MySQL server

  # Service configuration for MongoDB database
  mongodb:
    image: mongo:6.0  # Specifies the MongoDB image version 6.0
    container_name: mongodb  # Names the container as 'mongodb'
    env_file:
      - .env  # Loads environment variables from the .env file
    environment: # sets the environment variables for the container
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - "27017:27017"  # Maps port 27017 of the host to port 27017 of the container