services:
  # Service configuration for the Spring Boot application
  my-app:
    image: quentinformatique/path-pilotapi  # Specifies the Docker image for the application
    pull_policy: always  # Ensures the latest image is always pulled
    container_name: api  # Names the container as 'api'
    env_file:
      - .env  # Loads environment variables from the .env file
    ports:
      - "8080:8080"  # Maps port 8080 on the host to port 8080 in the container

  # Service configuration for MySQL database
  path-pilot-db-8:
    image: mysql:8.0.3  # Specifies the MySQL image version 8.0.3
    container_name: path-pilot-db-8  # Names the container as 'path-pilot-db-8'
    env_file:
      - .env  # Loads environment variables from the .env file
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}  # Sets the MySQL database name from the environment variable
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Sets the MySQL root password from the environment variable
      - MYSQL_USER=${MYSQL_USER}  # Sets the MySQL user from the environment variable
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  # Sets the MySQL user password from the environment variable
    ports:
      - "3306:3306"  # Maps port 3306 of the host to port 3306 of the container
    command: --character-set-server=utf8 --collation-server=utf8_general_ci  # Sets the character set and collation for the MySQL server

  # Service configuration for MongoDB
  mongodb:
    image: mongo:6.0  # Specifies the MongoDB image version 6.0
    container_name: mongodb  # Names the container as 'mongodb'
    env_file:
      - .env  # Loads environment variables from the .env file
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}  # Sets the MongoDB initial database name from the environment variable
    ports:
      - "27017:27017"  # Maps port 27017 on the host to port 27017 in the container