# Docker Compose configuration for the project
services:
  api:
    image: quentinformatique/path-pilotapi # Docker image for the application
    pull_policy: always # Policy to always pull the latest image
    container_name: path-pilot-api # Container name
    env_file:
      - ./.env # Loads environment variables from the .env file
    ports:
      - "8080:8080" # Port mapping: host port 8080 to container port 8080
    restart:
      on-failure # Restarts the container if it fails