services:
  # Service configuration for MySQL database
  mysql:
    image: mysql:8.0.3  # Specifies the MySQL image version 8.0.3
    container_name: path-pilot-mysql  # Names the container
    env_file:
      - ./.env # Loads environment variables from the .env file
    volumes:
      - ./init:/docker-entrypoint-initdb.d  # Mounts the 'init' directory to the MySQL initialization directory
    ports:
      - "3306:3306"  # Maps port 3306 of the host to port 3306 of the container, wich is the default MySQL port
    command: --character-set-server=utf8 --collation-server=utf8_general_ci  # Sets the character set and collation for the MySQL server

  # Service configuration for MongoDB database
  mongodb:
    image: mongo:6.0 # Specifies the MongoDB image version 6.0
    container_name: path-pilot-mongodb # Names the container
    env_file:
      - ../.env # Loads environment variables from the .env file
    volumes:
      - mongo-data:/data/db
      - ./init/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017" # Maps MongoDB ports