name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .

      - name: Save Docker image to a file
        run: docker save my-app:${{ github.sha }} -o my-app.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-image
          path: my-app.tar

      - name: Download Docker image artifact on EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: my-app.tar
          target: /home/${{ secrets.EC2_USER }}/my-app.tar

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load -i /home/${{ secrets.EC2_USER }}/my-app.tar
            echo "
            version: '3'
            services:
              path-pilot-db-8:
                image: mysql:8.0.3
                container_name: path-pilot-db-8
                environment:
                  - MYSQL_USER=pathpilot
                  - MYSQL_DATABASE=path-pilot
                  - MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }}
                  - MYSQL_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
                ports:
                  - '3306:3306'
                command: --character-set-server=utf8 --collation-server=utf8_general_ci

              mongodb:
                image: mongo:6.0
                container_name: mongodb
                environment:
                  - MONGO_INITDB_ROOT_USERNAME=root
                  - MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}
                  - MONGO_INITDB_DATABASE=path-pilot
                ports:
                  - '27017:27017'

              my-app:
                image: my-app:${{ github.sha }}
                container_name: my-app
                ports:
                  - '80:80'
                depends_on:
                  - path-pilot-db-8
                  - mongodb
            " > docker-compose.yml
            docker compose up -d