name: CD

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t path-pilotapi .
          docker tag path-pilotapi:latest ${{ secrets.DOCKER_USERNAME }}/path-pilotapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/path-pilotapi:latest

      - name: Create temporary SSH key file
        run: echo "${{ secrets.SSH_KEY }}" > temp_ssh_key.pem

      - name: Set permissions for SSH key file
        run: chmod 600 temp_ssh_key.pem

      - name: Upload docker-compose.yml to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i temp_ssh_key.pem docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/docker-compose.yml

      - name: Export environment variables and run Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i temp_ssh_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/path-pilotapi:latest
            sudo docker compose down
            sudo docker compose up -d
          EOF

      - name: Clean up temporary SSH key file
        run: rm temp_ssh_key.pem