name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run DB container
        run: docker compose up -d path-pilot-db-8-test
          | docker compose up -d mongodb

      - name: Check DB container
        run: docker ps

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle # Build the project without running tests
        run: ./gradlew build --no-daemon -x test

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Check code quality
        run: ./gradlew check --no-daemon

      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Archive JaCoCo report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html